//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expence
    {
        public Expence()
        {
            this.Verifications = new HashSet<Verification>();
        }
    
        public int expenceID { get; set; }
        public string type { get; set; }
    
        public virtual ICollection<Verification> Verifications { get; set; }
    }
}
