//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public Trip()
        {
            this.Vacations = new HashSet<Vacation>();
            this.Verifications = new HashSet<Verification>();
        }
    
        public int tripID { get; set; }
        public int origin { get; set; }
        public int destination { get; set; }
        public System.DateTime start { get; set; }
        public System.DateTime end { get; set; }
        public Nullable<int> prepayment { get; set; }
        public string note { get; set; }
        public int user { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<Vacation> Vacations { get; set; }
        public virtual ICollection<Verification> Verifications { get; set; }
        public virtual Boss Boss1 { get; set; }
    }
}
