//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacation
    {
        public int VacationID { get; set; }
        public System.DateTime start { get; set; }
        public System.DateTime end { get; set; }
        public int tripID { get; set; }
    
        public virtual Trip Trip { get; set; }
    }
}
