//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Verification
    {
        public int verificationID { get; set; }
        public int expenceID { get; set; }
        public double cost { get; set; }
        public string path { get; set; }
        public System.DateTime date { get; set; }
        public string note { get; set; }
        public int tripID { get; set; }
    
        public virtual Expence Expence { get; set; }
        public virtual Trip Trip { get; set; }
    }
}
